### ISSUE TITLE
[FE] 게임종료 기능 구현

### ISSUE THREAD

**Issue by silvertae** [gaemi-marble/gaemi-marble#1]
## ✅ ToDo
- [x] 게임종료 화면 UI 구현
- [x] gameOver 타입 메세지 관련 상태변경 로직 useGameReducer에 추가
- [x] 게임방 나가기 버튼 추가
