### ISSUE TITLE
[FE] 황금카드 기능

### ISSUE THREAD

**Issue by aaaz425** [gaemi-marble/gaemi-marble#23]
## ✅ ToDo
- [x] 황금카드 공통 컴포넌트
- [x] 기부 (선택 플레이어에게 현금 1000만 기부)
- [x] 주가 조작 (선택 기업 주가 +30%)
- [x] 악성 루머 양산 (선택 기업 주가 -30%)

## 🖐️ P.S. 
-
