### ISSUE TITLE
[FE] 플레이어 감정표현 기능 구현

### ISSUE THREAD

**Issue by silvertae** [gaemi-marble/gaemi-marble#28]
## ✅ ToDo
- [x] 감정표현 버튼 및 드롭다운 UI
- [x] 감정표현 기능 관련 웹소켓 메세지 구현
- [x] 서버와 연동해서 테스트
