### ISSUE TITLE
[BE] 추가 요구, 버그 픽스

### ISSUE THREAD

**Issue by HyowonSin** [gaemi-marble/gaemi-marble#55]
## ✅ ToDo
- [ ] 방 유효성 검사할 때 isPlaying 추가
- [ ] 리프레시 토큰 수정 어려우면 일단 액세스 토큰 만료 기한 늘리기
- [ ] 게임 시작 전 방 나갈 때 메세지 보내면 세션 끊어줄 수 있는지

## 🖐️ P.S. 
- 웹소켓 연결 끊길 게임 시작 전이면 세션 제거하면 될 듯
