### ISSUE TITLE
[FE] reducer 구조 개선

### ISSUE THREAD

**Issue by aaaz425** [gaemi-marble/gaemi-marble#60]
## ✅ ToDo
- [x] reducer 구조 개선
  - [x] switch문 내 타입 캐스팅 삭제
  - [x] switch case문 함수 분리
- [x] 불필요한 타입 제거

## 🖐️ P.S. 
-
