### ISSUE TITLE
[FE] useGameReducer 리팩터링 (feat. Jotai 상태 뿌수기)

### ISSUE THREAD

**Issue by silvertae** [gaemi-marble/gaemi-marble#7]
## ✅ ToDo
- [ ] 현재 Atom으로 관리하는 상태들 구조개편
- [ ] 비즈니스 로직들 useGameReducer -> action atom으로 변경하기
- [ ] 변경된 구조에 맞게 기존 코드들 리팩터링
